#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# add my custom bin //TODO: Clean this folder :D
export PATH=/Users/adam/Dropbox/Backup/Bash/bin:$PATH
# add homebrew & homebrew python path (wat?) //TODO: test without then remove
# export PATH=/usr/local/share/python:/usr/local/bin:/usr/local/sbin:$PATH
# add mamp php & mysql to my $PATH
export PATH=/Applications/MAMP/bin/php/php5.5.10/bin:$PATH