#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# colorful ls
export CLICOLOR=1

# NODE_PATH
export NODE_PATH=/usr/local/lib/node_modules

#
# aliases - shortcuts
#

# bash
alias cls="clear"
alias clr="clear"
alias ls="ls -AF"
alias lsd="ls -lh"
alias s="du -hs"
alias mv="mv -i"
alias rm="rm -i"
alias s2="slime2 -a"
alias s2.="s2 ."

#mysql
alias mysql="/Applications/MAMP/Library/bin/mysql"
alias mysqldump="/Applications/MAMP/Library/bin/mysqldump"

# postgresql
alias pgstart="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pgstop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
alias pgtail="tail -f /usr/local/var/postgres/server.log"

# middleman
alias mms="bundle exec middleman server"
alias mmb="bundle exec middleman build --clean"

# vagrant
alias vshare="vagrant share"
alias vssh="vagrant ssh"
alias vup="vagrant up"
alias vhalt="vagrant halt"
alias vreload="vagrant reload"
alias vcon="vagrant connect"
alias vconssh="vagrant connect --ssh"

# misc
alias ch="chrome-cli open" # chrome open new tab
alias gsch="ch https://github.com/adamkiss/prezto/tree/master/modules/git#aliases"
alias gsh="cat ~/.zprezto/modules/git/alias.zsh"
alias pwdcopy="printf '${PWD}' | pbcopy"
alias wdcopy="printf '${PWD##*/}' | pbcopy"

# set editor
export EDITOR='slime2'

# Doh Npm completion
eval "`npm completion`"