#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source secrets
source ~/.secrets

# Customize to your needs...

## colorful ls
export CLICOLOR=1

## NODE_PATH
export NODE_PATH=/usr/local/lib/node_modules

## PATH
# add my custom bin //TODO: Clean this folder :D
export PATH=/Users/adam/Dropbox/Backup/Bash/bin:$PATH

# add homebrew & homebrew python path (wat?) //TODO: test without then remove
# export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# add mamp php to my $PATH
# export PATH=/Applications/MAMP/bin/php/php7.0.0/bin:$PATH

# composer global
export PATH=/Users/adam/.composer/vendor/bin:$PATH

# yarn
# export PATH=$PATH:$HOME/.yarn/bin
export PATH="$PATH:`yarn global bin`"

## SDXC card shortcut
export SD=/Volumes/SDXC

## Caskroom PATH to link
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

## Winetricks
# export WINEPREFIX=/Volumes/data/Applications/Winetricks/
alias kmwinetricks="WINEPREFIX=/Volumes/data/Applications/Winetricks/ winetricks"
alias kmwine="WINEPREFIX=/Volumes/data/Applications/Winetricks/ wine"
alias kmwinesteam="WINEPREFIX=/Volumes/data/Applications/Winetricks/ wine C:\\\\windows\\\\command\\\\start.exe /Unix /Volumes/data/Applications/Winetricks/dosdevices/c:/users/Public/Desktop/Steam.lnk"

alias gwinetricks="WINEPREFIX=/Volumes/SDXC/Applications/Winetricks/ winetricks"
alias gwine="WINEPREFIX=/Volumes/SDXC/Applications/Winetricks/ wine"
alias gwinesteam="WINEPREFIX=/Volumes/SDXC/Applications/Winetricks/ wine C:\\\\windows\\\\command\\\\start.exe /Unix /Volumes/SDXC/Applications/Winetricks/dosdevices/c:/users/Public/Desktop/Steam.lnk"

#
# aliases - shortcuts
#

# bash
alias cls="clear"
alias clr="clear"
alias ls="ls -AF"
alias lsd="ls -lh"
alias s="du -hs"
alias mv="mv -i"
alias rm="rm -i"
f(){ find . -name *$1* }

#mysql
alias mysql="/Applications/MAMP/Library/bin/mysql"
alias mysqldump="/Applications/MAMP/Library/bin/mysqldump"

# postgresql
alias pgstart="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pgstop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
alias pgtail="tail -f /usr/local/var/postgres/server.log"

# middleman
alias mms="bundle exec middleman server"
alias mmb="bundle exec middleman build --clean"

# vagrant
alias vshare="vagrant share"
alias vssh="vagrant ssh"
alias vup="vagrant up"
alias vhalt="vagrant halt"
alias vreload="vagrant reload"
alias vcon="vagrant connect"
alias vconssh="vagrant connect --ssh"

# misc
alias ch="chrome-cli open" # chrome open new tab
alias gsch="ch https://github.com/adamkiss/prezto/tree/master/modules/git#aliases"
alias gsh="cat ~/.zprezto/modules/git/alias.zsh"
alias pwdcopy="printf '${PWD}' | pbcopy"
alias wdcopy="printf '${PWD##*/}' | pbcopy"

# mamp tail
alias lt-php="tail -f /Applications/MAMP/logs/php_error.log"
alias lt-apache="tail -f /Applications/MAMP/logs/apache_error.log"

# Frankensmith
# alias frank="rsync --info=progress2 -rL --exclude='.git' --exclude='.gitmodules' --exclude='.gitignore' --exclude='.DS_Store' --include='/.gitignore' ~/Projects/Frankensmith-site/"

# set editor
export EDITOR='slime'

# yarn run shortcut
alias yr="yarn run"

# Doh Npm completion
eval "`npm completion`"

# Bitbucket API stuff
function new_bitbucket_repo(){
	repo_args=( ${(s(/))1} )
	case $repo_args[1] in
		ak )
			user="adamkiss"
			;;
		akt )
			user="adamkissteam"
			project="project:={\"key\": \"AK${${2-B}:u}\"}"
			;;
		bs )
			user="bestshot"
			project="project:={\"key\": \"BS${${2-B}:u}\"}"
			;;
		* )
			user=$repo_args[1]
			;;
	esac
	repo=$repo_args[2]

	http -a adamkiss:${API_BITBUCKET} POST https://api.bitbucket.org/2.0/repositories/$user/$repo scm=git is_private:=true $project | jq -r '.links.clone[1].href'
}

function origin2bb(){
	git remote add origin `new_bitbucket_repo $1 $2`
}

function origin2bb_push(){
  origin2bb $1 $2 && git push -u origin master
}

function s2bb(){
	git remote remove origin && origin2bb $1 $2 && git push -u origin master
}
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# added by travis gem
[ -f /Users/adam/.travis/travis.sh ] && source /Users/adam/.travis/travis.sh

# Adding autocomplete for 'we'
[ -f ~/.we_autocomplete ] && source ~/.we_autocomplete
